Update patch set 6
Patch Set 6: Code-Review-1

As of now throws:

Uncaught TypeError: Property 'template' of object #<Object> is not a function.

in upload dashboard. Should be easy to fix.

Patch-set: 6