Update patch set 9
Patch Set 9: Code-Review+1

Ergg. This might not be possible to do cleanly.

There is a cyclic dependency here.

https://gerrit.wikimedia.org/r/#/c/362451/ is needed for the browser tests to pass.
However, if we merge that before this one, we'll get the following exception:

Notice: Array to string conversion in /Users/jrobson/git/core/includes/ServiceWiring.php on line 140

Fatal error: Class 'SkinArray' not found in /Users/jrobson/git/core/includes/ServiceWiring.php on line 141

I think we'll need to force merge this, ignore the browser tests THEN merge https://gerrit.wikimedia.org/r/#/c/362451/ to avoid any fatals in production. This will however break styling of the skin temporarily.

Patch-set: 9
Label: Code-Review=+1