Update patch set 13
Patch Set 13: Code-Review-1

Tests need to be updated:

awjrichards@ubuntu:/mnt/hgfs/testing/core/tests/phpunit$ make phpunit FLAGS="--group MobileFrontend"
php phpunit.php --configuration /mnt/hgfs/testing/core/tests/phpunit/suite.xml --group MobileFrontend
PHPUnit 3.7.7 by Sebastian Bergmann.

Configuration read from /mnt/hgfs/testing/core/tests/phpunit/suite.xml

..........................................................EEE   61 / 6654 (  0%)
.............................................................  122 / 6654 (  1%)
....................................................E..

Time: 3 seconds, Memory: 170.75Mb

There were 4 errors:

1) SkinMobileTest::testGetEnabledModules with data set #0 (array(array(array('beta')), array(array('beta', 'alpha'), 'top'), array(array('alpha'), 'bottom'), array(array('stable', 'beta')), array(array('stable')), array(array('?')), array('top')), 'Test', false, false, array(array(), array('juliusz', 'max')))
MWException: Call to undefined method SkinMobile::getEnabledModules

/mnt/hgfs/testing/core/includes/Skin.php:1565
/mnt/hgfs/wikimedia_git/extensions/MobileFrontend/tests/SkinMobileTest.php:88
/mnt/hgfs/wikimedia_git/extensions/MobileFrontend/tests/SkinMobileTest.php:88
/mnt/hgfs/testing/core/tests/phpunit/MediaWikiTestCase.php:116
/mnt/hgfs/testing/core/tests/phpunit/MediaWikiPHPUnitCommand.php:64
/mnt/hgfs/testing/core/tests/phpunit/MediaWikiPHPUnitCommand.php:48

2) SkinMobileTest::testGetEnabledModules with data set #1 (array(array(array('beta')), array(array('beta', 'alpha'), 'top'), array(array('alpha'), 'bottom'), array(array('stable', 'beta')), array(array('stable')), array(array('?')), array('top')), 'Test', true, false, array(array('brion'), array('arthur', 'juliusz')))
MWException: Call to undefined method SkinMobile::getEnabledModules

/mnt/hgfs/testing/core/includes/Skin.php:1565
/mnt/hgfs/wikimedia_git/extensions/MobileFrontend/tests/SkinMobileTest.php:88
/mnt/hgfs/wikimedia_git/extensions/MobileFrontend/tests/SkinMobileTest.php:88
/mnt/hgfs/testing/core/tests/phpunit/MediaWikiTestCase.php:116
/mnt/hgfs/testing/core/tests/phpunit/MediaWikiPHPUnitCommand.php:64
/mnt/hgfs/testing/core/tests/phpunit/MediaWikiPHPUnitCommand.php:48

3) SkinMobileTest::testGetEnabledModules with data set #2 (array(array(array('beta')), array(array('beta', 'alpha'), 'top'), array(array('alpha'), 'bottom'), array(array('stable', 'beta')), array(array('stable')), array(array('?')), array('top')), 'Test', true, true, array(array('brion'), array('jon')))
MWException: Call to undefined method SkinMobile::getEnabledModules

/mnt/hgfs/testing/core/includes/Skin.php:1565
/mnt/hgfs/wikimedia_git/extensions/MobileFrontend/tests/SkinMobileTest.php:88
/mnt/hgfs/wikimedia_git/extensions/MobileFrontend/tests/SkinMobileTest.php:88
/mnt/hgfs/testing/core/tests/phpunit/MediaWikiTestCase.php:116
/mnt/hgfs/testing/core/tests/phpunit/MediaWikiPHPUnitCommand.php:64
/mnt/hgfs/testing/core/tests/phpunit/MediaWikiPHPUnitCommand.php:48

4) MFResourceLoaderModuleTest::testGetTemplateScript with data set #1 (array(array('template', 'template2'), '/mnt/hgfs/wikimedia_git/extensions/MobileFrontend/tests/modules/../templates'), 'mw.mobileFrontend.template.add("template","hello\\n");mw.mobileFrontend.template.add("template2","goodbye\\n");')
MWException: MFResourceLoaderModule::getTemplateScript: template file not found: "/mnt/hgfs/wikimedia_git/extensions/MobileFrontend/tests/modules/../templates/template.html"

/mnt/hgfs/wikimedia_git/extensions/MobileFrontend/includes/modules/MFResourceLoaderModule.php:85
/mnt/hgfs/wikimedia_git/extensions/MobileFrontend/tests/modules/MFResourceLoaderModuleTest.php:142
/mnt/hgfs/testing/core/tests/phpunit/MediaWikiTestCase.php:116
/mnt/hgfs/testing/core/tests/phpunit/MediaWikiPHPUnitCommand.php:64
/mnt/hgfs/testing/core/tests/phpunit/MediaWikiPHPUnitCommand.php:48

FAILURES!
Tests: 177, Assertions: 193, Errors: 4.

Patch-set: 13
Label: Code-Review=-1