Fix 'TypeError: eventBus.bind is not a function' mobile.init error
This error can be seen (before this commit) by visiting the
Special:Watchlist page in mobile mode.

eventBus is an instance and not a function. Therefore, it does not have
a '.bind' property and this was throwing errors.

This commit fixes the error by wrapping it in a function.

Change-Id: I81bd0bb7a26571f843e3e402256b8f0540f54bd8