Update patch set 8
Patch Set 8:

(1 comment)

I think an error occurs when the editor is switched to VE:

Error: constructor must be a function, cannot be a undefined
    at OoFactory.oo.Factory.register (<anonymous>:71:751)
    at Object../src/mobile.editor.ve/ve.init.mw.MobileFrontendArticleTarget.js (load.php?debug=false&lang=en&modules=diffMatchPatch%2Cmoment%2Cpapaparse%2Crangefix%2Cspark-md5%2CtreeDiffer%2Cunicodejs|ext.visualEditor.articleTarget%2Cbase%2Ccore%2Cdata%2Cdiffing%2Cicons%2Clanguage%2Cmediawiki%2CmobileArticleTarget%2CmoduleIcons%2CmoduleIndicators%2Cmwalienextension%2Cmwcore%2Cmwextensionmessages%2Cmwextensions%2Cmwformatting%2Cmwgallery%2Cmwimage%2Cmwlanguage%2Cmwlink%2Cmwsave%2Cmwsignature%2Cmwtransclusion%2CsupportCheck%2Cwelcome|ext.visualEditor.core.mobile|ext.visualEditor.mwimage.core|ext.wikimediaEvents.visualEditor|jquery.lengthLimit|jquery.uls.data|mediawiki.ForeignApi%2Cwidgets|mediawiki.ForeignApi.core|mediawiki.diff.styles|mediawiki.language.names|mediawiki.page.gallery.styles|mediawiki.skinning.content.parsoid|mediawiki.widgets.MediaSearch%2CUserInputWidget%2Cstyles|mobile.editor.ve|oojs-ui.styles.icons-editing-list%2Cicons-editing-styling%2Cicons-layout%2Cicons-media%2Cicons-user%2Cicons-wikimedia&skin=minerva&version=0cvlkgm:1744)
    at f (<anonymous>:73:1759)
    at Object../src/mobile.editor.ve/mobile.editor.ve.js (load.php?debug=false&lang=en&modules=diffMatchPatch%2Cmoment%2Cpapaparse%2Crangefix%2Cspark-md5%2CtreeDiffer%2Cunicodejs|ext.visualEditor.articleTarget%2Cbase%2Ccore%2Cdata%2Cdiffing%2Cicons%2Clanguage%2Cmediawiki%2CmobileArticleTarget%2CmoduleIcons%2CmoduleIndicators%2Cmwalienextension%2Cmwcore%2Cmwextensionmessages%2Cmwextensions%2Cmwformatting%2Cmwgallery%2Cmwimage%2Cmwlanguage%2Cmwlink%2Cmwsave%2Cmwsignature%2Cmwtransclusion%2CsupportCheck%2Cwelcome|ext.visualEditor.core.mobile|ext.visualEditor.mwimage.core|ext.wikimediaEvents.visualEditor|jquery.lengthLimit|jquery.uls.data|mediawiki.ForeignApi%2Cwidgets|mediawiki.ForeignApi.core|mediawiki.diff.styles|mediawiki.language.names|mediawiki.page.gallery.styles|mediawiki.skinning.content.parsoid|mediawiki.widgets.MediaSearch%2CUserInputWidget%2Cstyles|mobile.editor.ve|oojs-ui.styles.icons-editing-list%2Cicons-editing-styling%2Cicons-layout%2Cicons-media%2Cicons-user%2Cicons-wikimedia&skin=minerva&version=0cvlkgm:1739)
    at f (<anonymous>:73:1759)
    at t (<anonymous>:73:1628)
    at Array.r [as push] (<anonymous>:73:1491)
    at load.php?debug=false&lang=en&modules=diffMatchPatch%2Cmoment%2Cpapaparse%2Crangefix%2Cspark-md5%2CtreeDiffer%2Cunicodejs|ext.visualEditor.articleTarget%2Cbase%2Ccore%2Cdata%2Cdiffing%2Cicons%2Clanguage%2Cmediawiki%2CmobileArticleTarget%2CmoduleIcons%2CmoduleIndicators%2Cmwalienextension%2Cmwcore%2Cmwextensionmessages%2Cmwextensions%2Cmwformatting%2Cmwgallery%2Cmwimage%2Cmwlanguage%2Cmwlink%2Cmwsave%2Cmwsignature%2Cmwtransclusion%2CsupportCheck%2Cwelcome|ext.visualEditor.core.mobile|ext.visualEditor.mwimage.core|ext.wikimediaEvents.visualEditor|jquery.lengthLimit|jquery.uls.data|mediawiki.ForeignApi%2Cwidgets|mediawiki.ForeignApi.core|mediawiki.diff.styles|mediawiki.language.names|mediawiki.page.gallery.styles|mediawiki.skinning.content.parsoid|mediawiki.widgets.MediaSearch%2CUserInputWidget%2Cstyles|mobile.editor.ve|oojs-ui.styles.icons-editing-list%2Cicons-editing-styling%2Cicons-layout%2Cicons-media%2Cicons-user%2Cicons-wikimedia&skin=minerva&version=0cvlkgm:1739
    at runScript (load.php?debug=false&lang=en&modules=startup&only=scripts&skin=minerva&target=mobile:12)
    at execute (load.php?debug=false&lang=en&modules=startup&only=scripts&skin=minerva&target=mobile:14)

Patch-set: 8