Update patch set 11
Patch Set 11: Code-Review-1

Visiting http://localhost:8080/wiki/Special:Nearby?debug=true

Watchstar.js:8 		toast = M.require( 'toast' ),
Error: Module not found: toast 


I also get a bunch more errors, but i think they are because of the one of the toast on the watchstar

Error: Module not found: modules/watchstar/Watchstar modules.js:17
Error: Module not found: modules/PageList modules.js:17
Error: Module not found: modules/nearby/Nearby modules.js:17
"hi from User:User/minerva.js" load.php:4
Error: Module not found: modules/PageList

Patch-set: 11
Label: Code-Review=-1