Hygiene: give JSDuck and JSDoc the ol' switcheroo
- Replace JSDuck with JSDoc. The config was copied from MinervaNeue.

- Upgrade mystery JSDoc dependency from v3.4.2 → v3.5.5. This dependency
  was not required previously but is now. The upgrade comes with many
  improvements but most notably fixes this error:

  Error: EISDIR: illegal operation on a directory, copyfile '/home/stephen/Code/wmf/vagrant/mediawiki/extensions/MobileFrontend/node_modules/jsdoc/templates/default/static/fonts/OpenSans-Bold-webfont.eot' -> 'docs/fonts'
    at Object.copyFileSync (fs.js:1697:3)
    at /home/stephen/Code/wmf/vagrant/mediawiki/extensions/MobileFrontend/node_modules/jsdoc/templates/default/publish.js:471:12
    at Array.forEach (<anonymous>)
    at Object.exports.publish (/home/stephen/Code/wmf/vagrant/mediawiki/extensions/MobileFrontend/node_modules/jsdoc/templates/default/publish.js:468:17)
    at Object.module.exports.cli.generateDocs (/home/stephen/Code/wmf/vagrant/mediawiki/extensions/MobileFrontend/node_modules/jsdoc/cli.js:430:39)
    at Object.module.exports.cli.processParseResults (/home/stephen/Code/wmf/vagrant/mediawiki/extensions/MobileFrontend/node_modules/jsdoc/cli.js:383:20)
    at module.exports.cli.main (/home/stephen/Code/wmf/vagrant/mediawiki/extensions/MobileFrontend/node_modules/jsdoc/cli.js:227:14)
    at Object.module.exports.cli.runCommand (/home/stephen/Code/wmf/vagrant/mediawiki/extensions/MobileFrontend/node_modules/jsdoc/cli.js:180:5)
    at /home/stephen/Code/wmf/vagrant/mediawiki/extensions/MobileFrontend/node_modules/jsdoc/jsdoc.js:103:9
    at Object.<anonymous> (/home/stephen/Code/wmf/vagrant/mediawiki/extensions/MobileFrontend/node_modules/jsdoc/jsdoc.js:104:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

- Remove custom JSDuck custom tag implementation. CommonTag was only
  used by SeeTag (@see) and that's built into JSDoc.

- Remove @ignore workarounds for JSDoc syntax in JSDuck:

    find resources tests -iname \*.js|
    xargs -rd\\n sed -ri '/@ignore$/d; s%@ignore\s+%%'

- Move an @inheritdoc in Skin.js below the description so it's not
  interpreted as an argument.

- Remove JSDuck config. There is no config / CLI syntax for specifying
  default externals so these are not identified which appears to be
  consistent with the implementation in Popups.

https://github.com/jsdoc3/jsdoc/releases/tag/3.4.3
https://github.com/jsdoc3/jsdoc/releases/tag/3.5.0
https://github.com/jsdoc3/jsdoc/releases/tag/3.5.1
https://github.com/jsdoc3/jsdoc/releases/tag/3.5.2
https://github.com/jsdoc3/jsdoc/releases/tag/3.5.3
https://github.com/jsdoc3/jsdoc/releases/tag/3.5.4
https://github.com/jsdoc3/jsdoc/releases/tag/3.5.5
http://usejsdoc.org/about-configuring-jsdoc.html
http://usejsdoc.org/about-commandline.html
http://usejsdoc.org/about-configuring-default-template.html

Bug: T188261
Depends-On: I8bcc03c7f5661a597308d4e023575178a3af54b1
Change-Id: I5ea10c0235471e05d10a7309f0657db318b15e66