Update patch set 4
Patch Set 4: Code-Review-1

(1 comment)

Inline comment about schema + I get:

Error: u'funnel' is a required property

when I switch from source to VE or do anything in VE.

Please test with eventlogging-devserver before submitting.

Patch-set: 4
Label: Code-Review=-1