Update patch set 2
Patch Set 2: Code-Review-1

This is probably my set up but the contributions page emits a database error with this patch:

/wiki/Special:Contributions/Stephen Wikimedia\Rdbms\DBQueryError from line 1243 of /vagrant/mediawiki/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
Query: SELECT rev_id,rev_page,rev_text_id,rev_timestamp,rev_minor_edit,rev_deleted,rev_len,rev_parent_id,rev_sha1,rev_comment AS `rev_comment_text`,NULL AS `rev_comment_data`,NULL AS `rev_comment_cid`,rev_user,rev_user_text,NULL AS `rev_actor`,rev_content_format,rev_content_model FROM `revision` WHERE (Array) AND ((rev_deleted & 12) != 12) ORDER BY rev_timestamp DESC LIMIT 51 
Function: SpecialMobileHistory::doQuery
Error: 1054 Unknown column 'Array' in 'where clause' (127.0.0.1)
Backtrace:

#0 /vagrant/mediawiki/includes/libs/rdbms/database/Database.php(1044): Wikimedia\Rdbms\Database->reportQueryError(string, integer, string, string, boolean)
#1 /vagrant/mediawiki/includes/libs/rdbms/database/Database.php(1438): Wikimedia\Rdbms\Database->query(string, string)
#2 /vagrant/mediawiki/extensions/MobileFrontend/includes/specials/SpecialMobileHistory.php(158): Wikimedia\Rdbms\Database->select(array, array, array, string, array, array)
#3 /vagrant/mediawiki/extensions/MobileFrontend/includes/specials/SpecialMobileContributions.php(76): SpecialMobileHistory->doQuery()
#4 /vagrant/mediawiki/extensions/MobileFrontend/includes/specials/MobileSpecialPage.php(57): SpecialMobileContributions->executeWhenAvailable(string)
#5 /vagrant/mediawiki/extensions/MobileFrontend/includes/specials/MobileSpecialPageFeed.php(23): MobileSpecialPage->execute(string)
#6 /vagrant/mediawiki/includes/specialpage/SpecialPage.php(522): MobileSpecialPageFeed->execute(string)
#7 /vagrant/mediawiki/includes/specialpage/SpecialPageFactory.php(579): SpecialPage->run(string)
#8 /vagrant/mediawiki/includes/MediaWiki.php(288): SpecialPageFactory::executePath(Title, RequestContext)
#9 /vagrant/mediawiki/includes/MediaWiki.php(861): MediaWiki->performRequest()
#10 /vagrant/mediawiki/includes/MediaWiki.php(524): MediaWiki->main()
#11 /vagrant/mediawiki/index.php(42): MediaWiki->run()
#12 /var/www/w/index.php(5): require(string)
#13 {main}

I did a `git pull && git submodule update --recursive --init && vagrant up  --provision && vagrant git-update`, confirmed I had `I8d825eb0`, and executed `mwscript update.php --server wiki`.

Patch-set: 2
Label: Code-Review=-1