Update patch set 2
Patch Set 2: Code-Review-1

This breaks alpha of Special:MobileOptions

 - Exception thrown by mobile.startup load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=minerva&version=20140917T…:150
TypeError: undefined is not a function TypeError 

I don't see the expand all options setting

Patch-set: 2
Label: Code-Review=-1