Update patch set 5
Patch Set 5:

Also breaks beta

Fatal error: Call to undefined method MobileTemplateBeta::get() in /Users/jrobson/Sites/w/extensions/MobileFrontend/includes/skins/SkinMobileBeta.php on line 38

Patch-set: 5