Update patch set 3
Patch Set 3: Code-Review+1

I've converted a property check to `prop in obj` and changed explicit boolean conversion to use the `Boolean` constructor instead of having and if.

I personally prefer using the String(x) constructor instead of `x.toString()` because it doesn't blow up if x is undefined/null. What do you guys think?

> a = null
null
> a.toString()
TypeError: Cannot call method 'toString' of null
> String(a)
'null'

Patch-set: 3
Reviewer: Jhernandez <2027@e9e9afe9-4712-486d-8885-f54b72dd1951>
Label: Code-Review=+1