Update patch set 6
Patch Set 6:

Switching with changes from VE to WTE and then WTE to VE results in an exception:

TypeError: Called on non-object
    at Object.oo.getObjectValues
    at VeInitMwMobileArticleTarget.ve.init.mw.ArticleTarget.parseMetadata
    at VeInitMwMobileArticleTarget.ve.init.mw.ArticleTarget.loadSuccess
    ...

Patch-set: 6
Reviewer: Bartosz Dziewoński <417@e9e9afe9-4712-486d-8885-f54b72dd1951>