Update patch set 18
Patch Set 18:

There's a valid lint error i think:

    Error: Missing messages used directly in file: resources/mobile.editor.overlay/EditorOverlay.js:
       In module mobile.editor.overlay, missing:
         visualeditor-mweditmode-tooltip

I'll have a look

Patch-set: 18