Update patch set 44
Patch Set 44:

> Patch Set 44: Code-Review+1
> 
> LGTM. I did experience this exception at one point (guessing caching related) so I'm not sure if this needs to be any more reslient, but I thought it would be important to mention it. Feel free to merge as you need.
> 
> Query.Deferred exception: (intermediate value)(intermediate value).setReadOnly is not a function TypeError: (intermediate value)(intermediate value).setReadOnly is not a function

Are you sure you were testing with the latest VisualEditor? setReadOnly was introduced relatively recently in a refactor (Ifaa74be266c048d87f94b4ae2df59cafc7aa155f).

Patch-set: 44
Reviewer: Bartosz Dziewoński <417@e9e9afe9-4712-486d-8885-f54b72dd1951>