Update patch set 42
Patch Set 42:

Hi do you know what causes this error

Fatal error: Unsupported operand types in /Users/jrobson/git/core/includes/registration/ExtensionProcessor.php on line 220.

I didn't test this new patch. but I can.

Patch-set: 42