Update patch set 44
Patch Set 44: Code-Review+1

LGTM. I did experience this exception at one point (guessing caching related) so I'm not sure if this needs to be any more reslient, but I thought it would be important to mention it. Feel free to merge as you need.

Query.Deferred exception: (intermediate value)(intermediate value).setReadOnly is not a function TypeError: (intermediate value)(intermediate value).setReadOnly is not a function

Patch-set: 44
Reviewer: Jdlrobson <94@e9e9afe9-4712-486d-8885-f54b72dd1951>
Label: Code-Review=+1