Update patch set 4
Patch Set 4: Code-Review-1

http://localhost:8080/wiki/Special:Uploads?mobileaction=alpha#/upload-tutorial/foo is throwing an error. 

"Exception thrown by mobile.upload.ui"

"TypeError: document.body is null" TypeError: document.body is null

 TypeError: Cannot read property 'scrollTop' of null 

ALso, left and right button padding are not the same. Right button looks good, but the left button touches the left border.

Patch-set: 4
Reviewer: Bmansurov <1963@e9e9afe9-4712-486d-8885-f54b72dd1951>
Label: Code-Review=-1